### ISSUE TITLE
Broken Transaction Proto

### ISSUE THREAD

**Issue by olibaron** [kulapio/libra-core#11]
Transaction.proto has been changed and RawTransaction is removed. Transfer needs to be rewritten.

**Comment by totiz** [comment]
Yes, I'm working on that, hope to make it done soon.

**Comment by olibaron** [comment]
You are porting LCS right?

**Comment by totiz** [comment]
In the Libra core itself (to upgrade protobuf and other stuffs), and this as well https://github.com/ketola/jlibra/tree/transaction-serialization, the communities are very active, I just finished porting protobuf.

**Comment by Yosuke-Aramaki** [comment]
Does the transaction bug fixed? It seems that we cannot transfer in demo page.

**Comment by totiz** [comment]
@Yosuke-Aramaki  not yet, LCS it takes time to implement. Hope to make it done soon.

**Comment by Yosuke-Aramaki** [comment]
OK, thank you for your comment. I hope you will fix soon !!

**Comment by totiz** [comment]
Fixed in https://github.com/kulapio/libra-core/releases/tag/v2.0.2
