### ISSUE TITLE
Key generation doesn't work with react-native #8

### ISSUE THREAD

**Issue by qalqi** [kulapio/libra-core#16]
This library is not working with react-native 0.59

Can you provide a polyfill for react-native?

**Comment by qalqi** [comment]
`error: bundling failed: Error: Unable to resolve module `memcpy` from `C:\Cloud\socialnetwork\mobile\node_modules\bytebuffer\dist\bytebuffer-node.js`: Module `memcpy` does not exist in the Haste module map`

**Comment by totiz** [comment]
@qalqi I've never use react-native before, but what's the version of kulap-libra that using? and may be if can PR for this.

**Comment by qalqi** [comment]
This line is causing the crash where we are importing node and grpc.
https://github.com/kulapio/libra-core/blob/03667db0df131ed258f6cd8cbac6e15ad1b64e2d/lib/client/index.ts#L84

Without that, it seems to be working. Still testing and will raise a PR

**Comment by turingpavan** [comment]
Tested in iPhone and Android. Here is PR for the https://github.com/kulapio/libra-core/pull/18

**Comment by totiz** [comment]
@turingpavan I just release v2.0.3, could you please update your lib and test https://github.com/kulapio/libra-core/releases/tag/v2.0.3

**Comment by qalqi** [comment]
Tested `v2.0.3`  Wallet, Network, Transactions are working fine. Will share a new issue if there any new.

Thanks!
